# Generated by Django 3.2.5 on 2023-02-22 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='code')),
                ('category_id', models.IntegerField(verbose_name='category_id')),
                ('category', models.CharField(max_length=128, verbose_name='category_title')),
                ('title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='info')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('available', models.IntegerField(verbose_name='available')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo')),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='avg_rating')),
                ('sale_quantity', models.IntegerField(verbose_name='sale_quantity')),
            ],
            options={
                'db_table': 'view_catalog',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='username')),
                ('saleday', models.DateTimeField(verbose_name='saleday')),
                ('catalog_id', models.IntegerField(verbose_name='catalog_id')),
                ('category', models.CharField(max_length=128, verbose_name='category')),
                ('title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='info')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='code')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='rating')),
                ('details', models.TextField(blank=True, null=True, verbose_name='review_details')),
                ('final', models.TextField(blank=True, null=True, verbose_name='final')),
            ],
            options={
                'db_table': 'view_sale',
                'ordering': ['saleday'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basketday', models.DateTimeField(auto_now_add=True, verbose_name='basketday')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
            ],
            options={
                'db_table': 'basket',
                'ordering': ['basketday'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='code')),
                ('title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('info', models.TextField(blank=True, null=True, verbose_name='info')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo')),
            ],
            options={
                'db_table': 'catalog',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='category_title')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryday', models.DateTimeField(auto_now_add=True, verbose_name='deliveryday')),
                ('movement', models.CharField(choices=[('Application accepted for processing', 'Application accepted for processing'), ('Goods in transit', 'Goods in transit'), ('Stock item', 'Stock item'), ('The application is closed, the goods have been delivered', 'The application is closed, the goods have been delivered')], default='М', max_length=64, verbose_name='movement')),
                ('details', models.TextField(blank=True, null=True, verbose_name='delivery_details')),
            ],
            options={
                'db_table': 'delivery',
                'ordering': ['deliveryday'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datei', models.DateTimeField(verbose_name='datei')),
                ('numb', models.IntegerField(verbose_name='numb')),
            ],
            options={
                'db_table': 'invoice',
                'ordering': ['datei'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title_organization')),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('phone', models.CharField(max_length=128, verbose_name='phone')),
            ],
            options={
                'db_table': 'organization',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleday', models.DateTimeField(auto_now_add=True, verbose_name='saleday')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='rating')),
                ('details', models.TextField(blank=True, null=True, verbose_name='review_details')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_catalog', to='product.catalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sale',
                'ordering': ['saleday'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['title'], name='organizatio_title_be9d2d_idx'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_organization', to='product.organization'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_delivery', to='product.sale'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_category', to='product.category'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_invoice', to='product.invoice'),
        ),
        migrations.AddField(
            model_name='basket',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_catalog', to='product.catalog'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_basket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['saleday'], name='sale_saleday_35a3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['datei'], name='invoice_datei_0a57d7_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['deliveryday'], name='delivery_deliver_395d39_idx'),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['title'], name='catalog_title_a1bae3_idx'),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['basketday'], name='basket_basketd_d70b82_idx'),
        ),
    ]
